development:
  adapter: postgresql
  encoding: unicode
  database: pinboarddev
  host: localhost
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

production:
  adapter: postgresql
  encoding: unicode
  database: pinboarddprod
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>
